name: reddit_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: verdana
      fonts:
        - asset: assets/fonts/verdana.ttf

  assets:
    # Drawer Menu
    - assets/images/drawer_menu/all.png 
    - assets/images/drawer_menu/browse_comm.png
    - assets/images/drawer_menu/create_comm.png
    - assets/images/drawer_menu/custom_feeds.png

    # Bottom Menu
    - assets/images/bottom_menu/chat.png 
    - assets/images/bottom_menu/comm.png 
    - assets/images/bottom_menu/create.png 
    - assets/images/bottom_menu/home.png 
    - assets/images/bottom_menu/inbox.png 

    # Post Item
    - assets/images/post_item/comment.png
    - assets/images/post_item/share.png
    - assets/images/post_item/vote_down.png
    - assets/images/post_item/vote_up.png

    # Others
    - assets/images/reddit_icon.png
    - assets/images/down_arrow.png
    - assets/images/right_arrow.png
    - assets/images/top_arrow.png
    - assets/images/hamburger_menu.png
    - assets/images/search.png


